# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET Framework Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Install MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet
    - name: Restore NuGet
      uses: nuget/setup-nuget@v2

    - name: Restore dependencies
      run: nuget restore dEngine.sln

    # Build MSBuild
    - name: Build
      run: msbuild dEngine.sln /p:Configuration=Release
